---
label: Project
hide_body: false
fields:
- name: titulo
  type: text
  config:
    required: false
  label: Titulo
- name: subtitulo
  type: text
  config:
    required: false
  label: Subtitulo
- name: content
  type: image_gallery
  config: {}
  label: Content
- name: softwares_used
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Softwares used
pages:
- projects/Otro-Proyecto.md
- projects/Para-Delfi.md
- projects/Proyecto-de-Prueba.md
